language: node_js

node_js:
  - '10'

cache:
  npm

install:
  - npm install

script:
  - npm run build

after_success:
  - npm run dist:prepare-archives

notifications:
  email:
    on_failure: change

deploy:
  provider: releases
  file: dist/*.{tgz}
  file_glob: true
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true